#!/bin/sh

# try to install zsh AND oh-my-zsh
echo "trying to install dependencies..."
sudo dnf install zsh wget curl neovim

if [[ -z $STOW_FOLDERS  ]]; then
    STOW_FOLDERS="nvim,hatbox,zsh"
fi

if  [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

# install oh-my-zsh
if [ ! -d ".oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "Remember! Oh-my-zsh overwrites .zshrc"
    echo "run: `mv .zshrc.pre-oh-my-zsh .zshrc` to complete the installation"
fi
